# Generated by Django 4.2.6 on 2023-10-23 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagelink',
            name='extension',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadimage',
            name='extension',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
